python -m mug_bench \
    --label set \
    --dataset set \
    --dataset_dir /home/felix.wernlein/project/datasets/Hearthstone-All-set/ \
    --modality all \
    --hidden_size 256 \
    --batch_size 128 \
    --learning_rate 2.5e-4 \
    --num_epochs 500 \
    --patience 15 \
    --iterations 1 \
    --robust_training all \
    --missing_training \
    --missing_rate 1.0 \
    --missing_modality image tab \
    --contrastive_learning \
    --learning_rate_contrastive 1e-4\
    --batch_size_contrastive 32 \
    --num_epochs_contrastive 500 \
    --patience_contrastive 10 \
    --top_k 5 \